name: Build and Package Binaries

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    name: Build Binary for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka

      - name: Build Binary
        run: |
          mkdir -p dist
          python -m nuitka --standalone --onefile anki_assign_tags.py --output-dir=dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: dist/

  build-windows:
    name: Build Binary for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka

      - name: Build Binary
        run: |
          mkdir dist
          python -m nuitka --standalone --onefile anki_assign_tags.py --output-dir=dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-binary
          path: dist/

  build-macos:
    name: Build Binary for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka

      - name: Build Binary
        run: |
          mkdir dist
          python -m nuitka --standalone --onefile anki_assign_tags.py --output-dir=dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-binary
          path: dist/
