name: Build and Package Binaries

on:
  push:
    branches:
      - main
jobs:
  build:
    name: build binaries
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build Binary
        run: |
          pyinstaller --onefile anki_assign_tags.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: linux-binary
          path: dist/anki_assign_tags

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: matrix.os == 'macos-latest'
        with:
          name: macos-binary
          path: dist/anki_assign_tags

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: windows-binary
          path: dist/anki_assign_tags.exe